site_name: Описание сервиса "Войны"
nav:
 - Home: index.md
 - Warriors:
     - "Измеение и удаление воина": warriors/updel.md
     - "Воины и их профессии": warriors/profession.md
 - Skills:
     - "Список навыков": skills/view.md

theme:
 name: material